# Generated by Django 5.0.6 on 2024-07-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workhour_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhour',
            name='hourly_rate',
        ),
    ]
