# Generated by Django 5.0.6 on 2024-07-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0005_alter_employee_id'),
        ('workhour_tracking', '0002_remove_workhour_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('why_absent', models.CharField(choices=[('sick', 'Sick Day'), ('holiday', 'Holiday'), ('personal', 'Personal')], max_length=50)),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_records.employee')),
            ],
        ),
    ]
