# Generated by Django 5.0.6 on 2024-07-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(choices=[('team_leader', 'Team Leader'), ('rcw', 'RCW'), ('srcw', 'SRCW')], max_length=20)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('bank', 'Bank')], max_length=20)),
                ('hourly_rate', models.DecimalField(choices=[(15.5, '15.50'), (13.5, '13.50'), (12.5, '12.50')], decimal_places=2, max_digits=5)),
            ],
        ),
    ]
