# Generated by Django 5.0.6 on 2024-07-03 17:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0003_alter_employee_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(choices=[(Decimal('15.50'), 15.5), (Decimal('13.50'), 13.5), (Decimal('12.50'), 12.5)], decimal_places=2, max_digits=5),
        ),
    ]
