# Generated by Django 5.0.6 on 2024-07-05 14:04

import employee_records.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0004_alter_employee_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=employee_records.models.EmployeeNumberField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
