# Generated by Django 5.0.6 on 2024-07-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_records', '0005_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
